# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd7556d40e649175af9e7bfe019e8f40f12acb904d3f9f63f2bf1b8998a6812860b68253a87a555b6cb12e406db2e88fb9a04c9ffd673dce1a4122dc2f4d26de

test:
  secret_key_base: 90423861b9da9381977fa0498943d05050b20801e59de30ac60645459659254b8d8188cd7012f077d073763bda40f54390330dab2a846c1a56f5d040b011b159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
